title: "extrawurst's blog"
author: "Stephan 'extrawurst' Dilly"
description: "Thoughts and random opinions of a Software Engineer, Manager and Consultant based in Germany"
#subheading: "Really cool blog about ... something"
more: "more..."
url: "http://extrawurst.github.io"
#baseurl: "/contrast" # comment out if in root directory

comments:
    disqus: "extrawurst"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github-square: "https://github.com/extrawurst"
  - twitter-square: "https://twitter.com/extrawurst"
  - linkedin-square: "https://www.linkedin.com/in/stephandilly"
  - xing-square: "https://www.xing.com/profile/Stephan_Dilly"
  - youtube-square: "https://www.youtube.com/user/ExtrawurstGames"
  - google-plus-square: "https://plus.google.com/u/0/+StephanDilly"
  - slideshare: "http://www.slideshare.net/Extrawurst"

gems:
  - jekyll-sitemap

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
